/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client_Joueur;

import gnu.io.CommPortIdentifier;
import java.util.Enumeration;
import javax.swing.DefaultListModel;

/**
 *
 * @author milan.teles
 */
public class ComPorts extends javax.swing.JDialog {

    private final DefaultListModel model;
    private String port;
    
    /**
     * Creates new form ComPorts
     * @param parent
     * @param modal
     */
    public ComPorts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        model = new DefaultListModel();
    }
    
    public void initialize() {
        this.setModalityType(ModalityType.MODELESS);
        
        Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();
        
        model.clear();
        
        while (portEnum.hasMoreElements()) {
            CommPortIdentifier currPortId = (CommPortIdentifier) portEnum.nextElement();
            model.addElement(currPortId.getName());
            System.out.println(currPortId.getName());
        }
        
        listComPorts.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listComPorts = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listComPorts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listComPorts);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!"".equals(listComPorts.getSelectedValue())) {
            port = listComPorts.getSelectedValue();
        }        
        doClose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void doClose() {
        setVisible(false);
        dispose();
    }
    
    public String getPort() {
        return port;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listComPorts;
    // End of variables declaration//GEN-END:variables
}
